name = "CurveFit"
uuid = "5a033b19-8c74-5913-a970-47c3779ef25c"
authors = ["Paulo José Saiz Jabardo <pjabardo@gmail.com> and contributors"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
LinearAlgebra = "1.10"
Markdown = "1.10.0"
NonlinearSolve = "4.8.0"
Polynomials = "4"
SciMLBase = "2.90"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "Test"]
